"""
app/server_fastapi.py
----------------------
FastAPI backend for the Game of Thrones face recognition app. Detects faces
in a video frame with MTCNN, embeds each face with FaceNet512, and only
returns a prediction when two independent methods - nearest-centroid
similarity and a trained classifier - agree AND each clears its own
confidence threshold.

Run from the project root: python app/server_fastapi.py
Interactive API docs (auto-generated by FastAPI): http://127.0.0.1:5002/docs

Extra dependencies beyond requirements.txt: fastapi, uvicorn, python-multipart
    pip install fastapi uvicorn python-multipart
"""
import sys
import os
import json
import asyncio
import logging
import threading
import webbrowser
import subprocess
from pathlib import Path

# On Windows, asyncio's default ProactorEventLoop logs noisy (harmless)
# tracebacks when a streaming connection (e.g. video range-requests) is
# still open at shutdown. SelectorEventLoop doesn't have this issue.
if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())


class _SuppressShutdownNoise(logging.Filter):
    """Hides the harmless CancelledError/ConnectionResetError tracebacks
    that asyncio/uvicorn log when Ctrl+C interrupts the server while a
    streaming response (e.g. video range-request) is still in flight.
    Any other error still gets logged normally."""
    _NOISY = ('CancelledError', 'ConnectionResetError', '_ProactorBasePipeTransport')

    def filter(self, record):
        if record.exc_info and record.exc_info[0] is not None:
            if record.exc_info[0].__name__ in self._NOISY:
                return False
        return not any(term in record.getMessage() for term in self._NOISY)


for _logger_name in ('asyncio', 'uvicorn.error'):
    logging.getLogger(_logger_name).addFilter(_SuppressShutdownNoise())

import numpy as np
import cv2
from PIL import Image
from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from starlette.requests import Request
import uvicorn

BASE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = BASE_DIR.parent
sys.path.insert(0, str(PROJECT_ROOT))

try:
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')
except AttributeError:
    pass

from deepface import DeepFace
import keras

from src.face_detector import detect_faces

app = FastAPI(title="CinefaceInsight")

UPLOAD_FOLDER = BASE_DIR / 'static' / 'uploads'
UPLOAD_FOLDER.mkdir(parents=True, exist_ok=True)

app.mount("/static", StaticFiles(directory=BASE_DIR / "static"), name="static")

templates = Jinja2Templates(directory=BASE_DIR / "templates")
# index.html references static files via url_for('static', filename=...).
# Registering that exact call signature as a template global resolves it
# to the /static mount above.
templates.env.globals['url_for'] = lambda name, **kwargs: (
    f"/static/{kwargs.get('filename', '')}" if name == 'static' else '/'
)

PORT = int(os.environ.get('PORT', 5002))
IS_HOSTED = bool(os.environ.get('SPACE_ID'))

FACENET_MODEL_NAME = 'Facenet512'
CLASSIFIER_PATH = str(PROJECT_ROOT / 'models' / 'facenet_classifier.keras')
CENTROID_DIR = str(PROJECT_ROOT / 'models' / 'centroids')
CLASS_NAMES_PATH = str(PROJECT_ROOT / 'models' / 'embeddings' / 'class_names.json')
INFO_PATH = str(PROJECT_ROOT / 'src' / 'info.json')

CENTROID_THRESHOLD = 0.60
CLASSIFIER_THRESHOLD = 0.80

try:
    with open(CLASS_NAMES_PATH) as f:
        class_names = json.load(f)
    print(f"✅ Loaded {len(class_names)} class names")
except Exception as e:
    print(f"❌ Error loading class names: {e}")
    class_names = []

try:
    centroids = np.zeros((len(class_names), 512), dtype=np.float32)
    for i, name in enumerate(class_names):
        centroids[i] = np.load(os.path.join(CENTROID_DIR, f'{name}.npy'))
    print(f"✅ Loaded {len(class_names)} centroid vectors")
except Exception as e:
    print(f"❌ Error loading centroids: {e}")
    centroids = None

try:
    classifier = keras.models.load_model(CLASSIFIER_PATH)
    print("✅ facenet_classifier.keras loaded successfully")
except Exception as e:
    print(f"❌ Error loading classifier: {e}")
    classifier = None

try:
    with open(INFO_PATH, 'r') as f:
        character_info = json.load(f)
    print("✅ Character info loaded successfully")
except Exception as e:
    print(f"❌ Error loading character info: {e}")
    character_info = {}


def cosine_sim(a, b):
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))


def get_embedding(pil_image):
    img_bgr = cv2.cvtColor(np.array(pil_image), cv2.COLOR_RGB2BGR)
    result = DeepFace.represent(
        img_path=img_bgr,
        model_name=FACENET_MODEL_NAME,
        detector_backend='skip',
        enforce_detection=False,
    )
    return np.array(result[0]['embedding'], dtype=np.float32)


def warm_up_model():
    try:
        dummy = np.zeros((160, 160, 3), dtype=np.uint8)
        DeepFace.represent(
            img_path=dummy,
            model_name=FACENET_MODEL_NAME,
            detector_backend='skip',
            enforce_detection=False,
        )
        print("✅ FaceNet512 warmed up")
    except Exception as e:
        print(f"⚠️ Warm-up failed (first real request will be slower): {e}")


@app.get("/")
def index(request: Request):
    return templates.TemplateResponse(request, "index.html", {})


@app.post("/upload_video")
async def upload_video(video: UploadFile = File(...)):
    if video.filename == '':
        raise HTTPException(status_code=400, detail="No file selected")

    allowed_extensions = ['mp4', 'avi', 'mov', 'mkv', 'webm']
    if not any(video.filename.lower().endswith(ext) for ext in allowed_extensions):
        raise HTTPException(status_code=400, detail="Invalid file type")

    path = UPLOAD_FOLDER / video.filename
    contents = await video.read()
    with open(path, 'wb') as f:
        f.write(contents)

    return {"video_path": str(path), "status": "success"}


@app.post("/detect_faces")
async def detect_frame_faces(frame: UploadFile = File(...)):
    try:
        contents = await frame.read()
        img = Image.open(__import__('io').BytesIO(contents)).convert('RGB')
        img = np.array(img)

        faces = detect_faces(img)

        if len(faces) == 0:
            return {"faces": [], "message": "No faces detected"}

        print(f"✅ Detected {len(faces)} faces")
        return {"faces": faces, "count": len(faces)}

    except Exception as e:
        print(f"❌ Error in face detection: {e}")
        raise HTTPException(status_code=500, detail=f"Face detection failed: {str(e)}")


@app.post("/predict_face")
async def predict_face(face: UploadFile = File(...)):
    try:
        if classifier is None or centroids is None or not class_names:
            raise HTTPException(status_code=500, detail="Model not loaded")

        contents = await face.read()
        img = Image.open(__import__('io').BytesIO(contents)).convert('RGB')

        if img.width < 5 or img.height < 5:
            raise HTTPException(status_code=400, detail="Face crop too small, try a different frame")

        embedding = get_embedding(img)

        sims = np.array([cosine_sim(embedding, c) for c in centroids])
        centroid_idx = int(np.argmax(sims))
        centroid_name = class_names[centroid_idx]

        probs = classifier.predict(embedding[np.newaxis, :], verbose=0)[0]
        classifier_idx = int(np.argmax(probs))
        classifier_name = class_names[classifier_idx]
        classifier_confidence = float(probs[classifier_idx])

        print(f"  centroid says:   {centroid_name} (similarity={sims[centroid_idx]:.3f})")
        print(f"  classifier says: {classifier_name} (confidence={classifier_confidence:.3f})")

        centroid_similarity = float(sims[centroid_idx])

        if centroid_name != classifier_name:
            print(f"⚠️ Disagreement ({centroid_name} vs {classifier_name}) — treating as unclear")
            return {
                "status": "low_confidence",
                "confidence": classifier_confidence,
                "message": "Couldn't confidently recognize this face. Try a clearer frame — or this may not be one of the 15 main characters this model knows."
            }

        if centroid_similarity < CENTROID_THRESHOLD:
            print(f"⚠️ Agreed on {centroid_name} but centroid similarity too low ({centroid_similarity:.2f} < {CENTROID_THRESHOLD}) — treating as unclear")
            return {
                "status": "low_confidence",
                "confidence": classifier_confidence,
                "message": "Couldn't confidently recognize this face. Try a clearer frame — or this may not be one of the 15 main characters this model knows."
            }

        if classifier_confidence < CLASSIFIER_THRESHOLD:
            print(f"⚠️ Agreed on {centroid_name} but classifier confidence too low ({classifier_confidence:.2f} < {CLASSIFIER_THRESHOLD}) — treating as unclear")
            return {
                "status": "low_confidence",
                "confidence": classifier_confidence,
                "message": "Couldn't confidently recognize this face. Try a clearer frame — or this may not be one of the 15 main characters this model knows."
            }

        info = character_info.get(centroid_name, 'No info available')
        print(f"✅ Both methods agree: {centroid_name} (confidence: {classifier_confidence:.2f})")

        return {
            "prediction": centroid_name,
            "info": info,
            "confidence": classifier_confidence,
            "status": "success"
        }

    except HTTPException:
        raise
    except Exception as e:
        print(f"❌ Error in face prediction: {e}")
        raise HTTPException(status_code=500, detail=f"Prediction failed: {str(e)}")


def open_browser():
    url = f"http://127.0.0.1:{PORT}/"
    chrome_paths = [
        r"C:\Program Files\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
        os.path.expandvars(r"%LOCALAPPDATA%\Google\Chrome\Application\chrome.exe"),
    ]
    for chrome_path in chrome_paths:
        if os.path.isfile(chrome_path):
            subprocess.Popen([chrome_path, "--start-maximized", "--new-window", url])
            return
    webbrowser.open_new(url)


if __name__ == '__main__':
    print(f"🚀 Starting FastAPI FaceNet application on port {PORT}...")
    warm_up_model()
    if not IS_HOSTED:
        threading.Timer(1.25, open_browser).start()
    uvicorn.run(app, host='0.0.0.0', port=PORT)
